### PR TITLE
[ci skip] [cf admin skip] ***NO_CI*** Add fcollonval as maintainer

### PR DESCRIPTION
**Pull request by fcollonval**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fcollonval** [comment]
Hey @asford thanks for creating this recipe. The project was recently moved to a community organization for JupyterLab extensions. Would you mind adding me as maintainer as well to help with the maintenance?

@ianhi @axelfahy you may be interested to be added as maintainer as well?

**Comment by fcollonval** [comment]
@conda-forge-admin, please rerender

**Comment by asford** [comment]
Happy to, can you fix the build?

**Comment by ianhi** [comment]
> @ianhi @axelfahy you may be interested to be added as maintainer as well?

Yup that'd be great. And I second the thanks to @asford  for creating this!

**Comment by fcollonval** [comment]
> Yup that'd be great

Done

**Review by asford — APPROVED** [review]

**Comment by asford** [comment]
Can merge whenever you're ready.

**Comment by fcollonval** [comment]
Thanks @asford let's merge. If Axel replies, I'll add him in follow-up PR.

**Comment by fcollonval** [comment]
Thanks @asford let's merge. If Axel replies, I'll add him in follow-up PR.

**Comment by asford** [comment]
Pleasure doing business with you. 🔑 🚗 
Try not to crash 'er on the way off the lot. 😉

**Pull request merged**
